### ISSUE TITLE
adal.adal_error.AdalError: Server returned an unknown AccountType: unknown

### ISSUE THREAD

**Issue by jufei** [cmberryau/pypowerbi#24]
hi:
I am going to retrieve data from a report like: 

https://app.powerbi.com/groups/me/apps/d9690d83-440d-48ec-ab79-69814b1fed25/reports/2199edae-e0d7-4761-8495-f84a3c98439c/ReportSectione2e9c77b50eb527393f7?ctid=5d471751-9675-428d-917b-70f44f9630b0

So I tried like your example:

```python
import adal
from pypowerbi.client import PowerBIClient
from pypowerbi.dataset import Column, Table, Dataset

authority_url = 'https://login.windows.net/common'
resource_url = 'https://analysis.windows.net/powerbi/api'
api_url = 'https://api.powerbi.com'

# change these to your credentials
client_id = 'd9690d83-440d-48ec-ab79-69814b1fed25'
username = 'myemailaddress'
password = 'mypassword'

# first you need to authenticate using adal
logger.info('init context...')
context = adal.AuthenticationContext(authority=authority_url,
                                     validate_authority=True,
                                     api_version=None)
logger.info('init context done')

logger.info('acquire token...')
token = context.acquire_token_with_username_password(resource=resource_url,
                                                     client_id=client_id,
                                                     username=username,
                                                     password=password)
logger.info('got token: {}'.format(token))

# create your powerbi api client
logger.info('create client ...')
client = PowerBIClient(api_url, token)
logger.info('create client done.')

```

But I got the following error in acquire token:

``` bash

[root@Server_130 try]# python3 a.py
20-09-04 16:27:43 [ INFO] init context...
20-09-04 16:27:43 [ INFO] init context done
20-09-04 16:27:43 [ INFO] acquire token...
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - Authority:Performing instance discovery: ...
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - Authority:Performing static instance discovery
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - Authority:Authority validated via static instance discovery
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - TokenRequest:Acquiring token with username password.
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - CacheDriver:Found 0 potential entries.
20-09-04 16:27:43 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - UserRealm:Performing user realm discovery at: ...
20-09-04 16:27:43 [DEBUG] Starting new HTTPS connection (1): login.windows.net:443
20-09-04 16:27:44 [DEBUG] https://login.windows.net:443 "GET /common/UserRealm/fei.ju%40nokia-sbel.com?api-version=1.0 HTTP/1.1" 200 136
20-09-04 16:27:44 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - UserRealm:User Realm Discovery Server returned this correlation_id: d874be3e-0eff-439b-a6d6-bf65d28b46fd
20-09-04 16:27:44 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - UserRealm:Discovery response:
 {"ver":"1.0","account_type":"Unknown","cloud_instance_name":"microsoftonline.com","cloud_audience_urn":"urn:federation:MicrosoftOnline"}
20-09-04 16:27:44 [DEBUG] d874be3e-0eff-439b-a6d6-bf65d28b46fd - UserRealm:UserRealm response:
 AccountType: unknown
 FederationProtocol: None
 FederationMetatdataUrl: None
 FederationActiveAuthUrl: None
20-09-04 16:27:44 [ INFO] d874be3e-0eff-439b-a6d6-bf65d28b46fd - TokenRequest:get_token_func returned with error
Traceback (most recent call last):
  File "a.py", line 54, in <module>
    password=password)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 286, in get_token_with_username_password
    "Server returned an unknown AccountType: {}".format(self._user_realm.account_type))
adal.adal_error.AdalError: Server returned an unknown AccountType: unknown

```

**Comment by cmberryau** [comment]
Looks like you've got an AdalError there, I am not an expert on the adal package or the auth flow - so I would recommend looking there first.

**Comment by jotradovec** [comment]
@jufei Did you solved this?
I have run into same error following this: https://learn.microsoft.com/en-us/information-protection/develop/concept-authentication-acquire-token-py
